# Generated by Django 4.2.7 on 2023-11-15 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=50)),
                ('year_of_publication', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)])),
                ('short_about', models.CharField(max_length=128)),
                ('about', models.CharField(max_length=512)),
                ('last_used', models.DateTimeField(blank=True)),
            ],
        ),
    ]
