# Generated by Django 4.2.7 on 2023-11-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
