# Generated by Django 4.2.7 on 2023-11-22 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='total_reading_time',
            new_name='total_reading_time_for_the_last_week',
        ),
        migrations.AddField(
            model_name='visitor',
            name='total_reading_time_for_the_last_month',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
