# Generated by Django 4.2.7 on 2023-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_readingstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='total_reading_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
