# Generated by Django 4.2.7 on 2023-11-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('visitors', '0003_alter_visitor_total_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='books.book'),
        ),
    ]
